name: InSpec Tools Workflow
on:
  push:
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        #os: [windows-latest, windows-2019, windows-2016, ubuntu-latest, ubuntu-18.04, ubuntu-16.04, macOS-latest, macOS-10.14]
        ruby: [2.4]
    steps:
      - uses: actions/checkout@v1
      - name: Use Ruby ${{ matrix.ruby }} on ${{ matrix.os }}
        uses: actions/setup-ruby@v1
      - name: install latest bundler
        run: |
          gem install bundler
      - name: bundle install
        run: |
          bundle install
      - name: rake test
        run: |
          rake test
      - name: install rubocop
        run: |
          gem install rubocop
      - name: rubocop
        run: |
          #rubocop
      - name: gem build
        run: | 
          gem build inspec_tools.gemspec
      - name: gem install
        run: |
          gem install inspec_tools
      - name: run
        run: |
          inspec_tools
        env:
          CI: true
        
