name: Changelog Generator
on:
  release:
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        #os: [windows-latest, windows-2019, windows-2016, ubuntu-latest, ubuntu-18.04, ubuntu-16.04, macOS-latest, macOS-10.14]
        ruby: [2.4]
    steps:
      - uses: actions/checkout@v1
      - name: Use Ruby ${{ matrix.ruby }} on ${{ matrix.os }}
        uses: actions/setup-ruby@v1
      - name: install changelog-generator
        run: |
          gem install github_changelog_generator
          github_changelog_generator -u djhaynes -p inspec_tools
          git commit -m "Updating changelog" CHANGELOG.md
          git push
        env:
          CI: true
