name: Test
on:
  push:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: djhaynes/github-version-action
        with:
          token: ${{secrets.GITHUB_TOKEN}}   
