name: Test Action    
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Test
        uses: djhaynes/github-version-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}   
