name: Version Information Generator
on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        #os: [windows-latest, windows-2019, windows-2016, ubuntu-latest, ubuntu-18.04, ubuntu-16.04, macOS-latest, macOS-10.14]
    steps:
      - name: get repo
        uses: actions/checkout@v1  
        with:
          token: ${{secrets.GITHUB_TOKEN}}   
      - name: get version information
        run: |
          git rev-list --tags --max-count=1 >> VERSION.md
          #git describe --tags $COMMIT
          #git show -s $TAG > VERSION.md
      - name: push
        uses: github-actions-x/commit@v2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'publish version information'
          force-add: 'true'
        env:
          CI: true
          #latest_commit: git rev-list --tags --max-count=1
          #latest_tag: git describe --tags ${{ latest_commit }}


