name: Version Information Generator
on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: get repo
        uses: actions/checkout@v1  
        with:
          token: ${{secrets.GITHUB_TOKEN}}   
      - name: get version information
        run: |
          echo "**Release:** " > VERSION.md
          git describe --tags $(git rev-list --tags --max-count=1) >> VERSION.md
          echo "<br><br>**Date:** " >> VERSION.md
          git show -s --format=%ci $(git rev-list --tags --max-count=1) >> VERSION.md
          echo "<br><br>**Commit:** " >> VERSION.md
          git rev-list --tags --max-count=1 >> VERSION.md
      - name: push
        uses: github-actions-x/commit@v2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'publish version information'
          force-add: 'true'
        env:
          CI: true


